### PR TITLE
resource allocation-related fixes, etc

### LINKED ISSUE #92: scheduler should property allocate driver-port for etcd-mesos-executor
... and then the custom executor should bind to that port when setting up the driver instance.

### PR DESCRIPTION
**Pull request by jdef**
* fixes #92: properly allocate libprocess port for executor driver
* fix resource allocation to take into account executor resources
* executor should attempt to use LIBPROCESS_IP as binding address for compat on multihomed hosts
* don't launch the executor in shell mode: it's a simple command w/ a simple set of args
* fix some govet and `make test` errors

### CODE REVIEW

**Comment by spacejam** [comment]
LGTM!  Feel free to merge at your convenience

File: cmd/etcd-mesos-executor/app.go [hunk 1]
```diff
@@ -29,15 +31,29 @@ import (
...
+	if *driverPort == 0 {
+		log.Fatal("missing or incorrectly specified driver-port flag, must be > 0")
+	}
 	log.Infoln("Starting etcd Executor")
 
+	var address net.IP
+	if libprocessIP := os.Getenv("LIBPROCESS_IP"); libprocessIP != "" {
+		address = net.ParseIP(libprocessIP)
+		if address == nil {
+			log.Warning("failed to parse IP address from LIBPROCESS_IP envvar %q", libprocessIP)
```
Comment (jdef) [inline cmd/etcd-mesos-executor/app.go]: s/Warning/Warningf/
